shape: [ 640, 640 ]

half: False

# optimizer
optim: Adam
lr: 0.01
momentum: 0.937
weight_decay: 0.0005

# scheduler
one_cycle: True
lrf: 0.01

# ema
ema_decay: 0.9999
tau: 2000

# early stop
patience: 50

warmup_epoch: 3
warmup_bias_lr: 0.1
warmup_momentum: 0.8


num_batch_size: 4
batch_size: 2
epochs: 1
njobs: 1

close_mosaic: 10
close_affine: 10

# loss
alpha: 1
beta: 1
topk: 3
box_w: 1
cls_w: 1
dfl_w: 1


# NMS
conf_t: 0.25
multi_label: False
max_box: 30000
max_wh: 7680
iou_t: 0.7
max_det: 300
merge: False

# 图像增强
mosaic: True # 是否采用Mosaic
affine: True # 是否采用仿射变换
hsv: 0.5 # 随机HSV增强
flipud: 0 # 随机上下翻转
fliplr: 0.5 # 随机左右翻转
scale: 0.5 # 仿射变换：图像尺寸放缩
translate: 0.1 # 仿射变换：图像平移
h: 0.015  # HSV：H
s: 0.7 # HSV：S
v: 0.4 # HSV：V
box_t: 5 # 最小检测目标尺寸
wh_rt: 10 # 目标长宽比过滤阈值
